name: publish

on:
  release:
    types: [published]

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: chrislennon/action-aws-cli@v1.1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - uses: actions/setup-node@v2
      with:
        node-version: 18.17.0
        cache: npm

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
