name: test

on:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 18.17.0
        cache: npm

    - name: Dependencies
      run: make install

    - name: env check
      run: env

    - name: Unit Tests
      run: make test
